### ISSUE TITLE
Unable to find required plugin jar

### ISSUE THREAD

**Issue by iamrahul127** [KongZ/charts#127]
**Describe the bug**
I have installed latest graylog version 4.2.3-1 using chart version 2.1.7. I need to integrate this graylog instance with Azure OpenId connect which requires a service creation in graylog. [OIDC integration](https://docs.graylog.org/docs/openid-connect#configuration). 

I tried creating service multiple times but nothing happens when I click on "Create Service" button. As per [help ticket](https://community.graylog.org/t/create-service-for-oidc-integration-failing-without-any-error/25886) raised & suggestion given my multiple community members I must install `graylog-enterprise-plugins graylog-integrations-plugins graylog-enterprise-integrations-plugins` plugins.  

To install plugins, I would need jar files which can be then configured under `plugins:` section in helm chart. I am finding it difficult to get jar file locations. Googled a lot but not finding anything. 
I understand this is not problem itself with chart but requesting help as I need to solve this desperately. 

I found that https://github.com/Graylog2/fpm-recipes/blob/c408eb6f66d0c0a2ed53c2ac05730396e43e19f3/recipes/data.yml has links to the plugins which probably can be used but they are in `tgz` format and not the `jar`. For example https://packages.graylog2.org/releases/graylog-enterprise/graylog-enterprise-4.3.7.tgz. 

Can I use `tgz` instead of `jar` ? Can someone help please? 

**Version of Helm and Kubernetes**:

Helm Version:

```console
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

Kubernetes Version:

```console
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"ece9ecf2f9aecbd86d3eba31f0be62e4b6353a5a", GitTreeState:"clean", BuildDate:"2022-07-28T23:33:17Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

**Which version of the chart**:
2.1.7

**OS Information**

- Azure Kubernetes Service
- PRETTY_NAME="Ubuntu 22.04.1 LTS" NAME="Ubuntu" VERSION_ID="22.04" VERSION="22.04.1 LTS (Jammy Jellyfish)" VERSION_CODENAME=jammy ID=ubuntu ID_LIKE=debian
- Graylog 4.3.7+05bccc7 on XXXXXXX.svc.cluster.local (Temurin 1.8.0_345 on Linux 5.4.0-1083-azure)

**Comment by KongZ** [comment]
You can use tgz file and it will extract before installation process.
You should be able to see a log `Extracting xxxx ...` when use tgz file

**Comment by iamrahul127** [comment]
Thank you for quick reply. I figure it out by looking into https://github.com/KongZ/charts/blob/d4633d218bf9c333d94cc529584484e3d944fd8f/charts/graylog/templates/configmap.yaml but didn't close issue yesterday.
