### ISSUE TITLE
Issue in setting up Graylog with default installation procedure

### ISSUE THREAD

**Issue by Ahmad-Faizan** [KongZ/charts#128]
We are trying to set up a Graylog cluster with a MongoDB operator and OpenSearch.

Tried to use this Helm chart to setup in a minikube cluster as well as a bare metal cluster. Following the readme does not set the whole thing up correctly as Graylog is not able to connect to MongoDB.

The MongoDB operator creates a default database instance too and the MongoURI is similar to the one provided in the Readme of this chart. But on checking the logs inside the Graylog pod, we found that it is able to connect to the ReplicaSet, but fails to authenticate.

These were the steps I followed : 
```
# install MongoDB from bitnami repo
helm install --namespace "graylog" mongodb bitnami/mongodb

# install OpenSearch
helm install --namespace "graylog" opensearch opensearch/opensearch

# install Graylog
helm install --namespace "graylog" graylog kongz/graylog \
  --set tags.install-mongodb=false\
  --set tags.install-elasticsearch=false\
  --set graylog.mongodb.uri=mongodb://mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.graylog.svc.cluster.local:27017/graylog?replicaSet=rs0 \
  --set graylog.elasticsearch.hosts=http://opensearch-cluster-master.graylog.svc.cluster.local:9200
  --set graylog.elasticsearch.version=7
```

Any improvement to the Readme on how setup Graylog to correctly talk to MongoDB will be of great use.

**Comment by KongZ** [comment]
In case of your mongodb requires authentication, you can provide user/pass on mongodb.uri e.g. `mongodb://user:pass@mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.graylog.svc.cluster.local:27017/graylog?replicaSet=rs0`

**Comment by Ahmad-Faizan** [comment]
Thanks @KongZ 
It resolved the issue after adding authentication to the URL.
