### ISSUE TITLE
presStop hook to set is_master = true to another node when existing master down 

### ISSUE THREAD

**Issue by pparthesh** [KongZ/charts#145]
When existing master node down/terminating state, cluster running without master node.

Helm Version: 3.10
Kubernetes Version: 1.26
Chart Version: latest

**What happened**:

When master node down I don't know how graylog handle the incoming request and process the same. Once master node down, k8s will take few minutes to bring up the pod and select the same as master.

**What you expected to happen**:

Add preStop hook which promote other pod to master via changing is_master = true label

**How to reproduce it**

Deploy graylog helm chart with default value and delete master node manually.

**Comment by KongZ** [comment]
You will need to restart the node in order to set it as a new master. This will cause you to lose 2 nodes at the same time. 1st original master, 2nd promoting master.It causes more trouble than waiting for the original master node to restart.
Graylog uses master only for rotating indexes.

**Comment by pparthesh** [comment]
noted
