### ISSUE TITLE
Upgrade to 4.0.2 image fails. Entrypoint and ConfigMap need adjustments.

### ISSUE THREAD

**Issue by juliohm1978** [KongZ/charts#20]
**Describe the bug**
The chart is unable to deploy using the newest docker image 4.0.2-1.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**: 1.7.2

**What happened**:
Just tried to upgrade to the new  docker image using this chart and the release fails with missing plugins. The Graylog pod crashes with the error message:

```
2021-01-28 18:17:40,213 ERROR   [CmdLineTool] - Guice error (more detail on log level debug): No implementation for java.util.Map<org.graylog2.plugin.Version, javax.inject.Provider<org.graylog.events.search.MoreSearchAdapter>> was bound.
  Did you mean?
    org.graylog2.plugin.Version annotated with @com.google.inject.name.Named(value=elasticsearch_version) bound  at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

    org.graylog.events.search.MoreSearchAdapter bound  at org.graylog2.storage.VersionAwareStorageModule.configure(VersionAwareStorageModule.java:54)

    org.graylog2.plugin.Version annotated with interface org.graylog2.storage.ElasticsearchVersion bound  at org.graylog2.bindings.ElasticsearchModule.configure(ElasticsearchModule.java:28)
 - {}
```

I raised the issue to the Docker image project (https://github.com/Graylog2/graylog-docker/issues/150). But it turns out, the official image changed the entrypoint. It handles plugin directories in a different way.

Since the chart injects a custom entrypoint, it is unaware of the new directory structure and fails to copy the necessary plugins in order to start Graylog correctly with basic Elasticsearch support.

**What you expected to happen**: The chart needs to support the official docker image _as is_.

**How to reproduce it** (as minimally and precisely as possible):
Manually update values.yaml with:

```
graylog:
  image:
    repository: "graylog/graylog:4.0.2-1"
```

**Comment by sergevs** [comment]
Workaround:
```
graylog:
   envRaw:
      - name: GRAYLOG_PLUGIN_DIR
         value: /usr/share/graylog/plugins-default
```

**Comment by KongZ** [comment]
I have release version 1.7.4 which support Graylog 4.0.2 image.
You may need to set `graylog.elasticsearch.version` if you want to use Elasticsearch 7

https://github.com/KongZ/charts/blob/main/charts/graylog/values.yaml#L297

**Comment by juliohm1978** [comment]
Thank you!

Would it still be possible to use `graylog.elasticsearch.version=6`. We are still under 6.8.

**Comment by KongZ** [comment]
@juliohm1978 yes, the default is version `6`
