### ISSUE TITLE
[feature] add support for graylog-plugin-integrations

### ISSUE THREAD

**Issue by sblack4** [KongZ/charts#28]
Graylog published the integrations plugin as either the source code or a `.tgz` but the chart wants it as a `.jar` it can `curl`. I think they should just publish the jar so I opened an issue there https://github.com/Graylog2/graylog-plugin-integrations/issues/721. In the mean time it would be nice to have a way to install is like you did with `.Values.graylog.metrics.enabled`.

**Comment by sblack4** [comment]
My quick hack-around was to just build a container with the plugin. Feel free to use/fork
- repo: https://github.com/rhythmictech/docker-graylog-integrations-plugin
- image: https://github.com/orgs/rhythmictech/packages/container/package/graylog-integrations-plugin

**Comment by KongZ** [comment]
I havn't tested yet but it should work #29
