### ISSUE TITLE
gh action sync-readme workflow fails because gh-pages branch is protected

### ISSUE THREAD

**Issue by scottrigby** [KongZ/charts#3]
See https://github.com/KongZ/charts/runs/1364678753
> remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/KongZ/charts
 ! [remote rejected] gh-pages -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'https://github.com/KongZ/charts'
Error: Process completed with exit code 1.

**Comment by KongZ** [comment]
Remove `gh-pages` branch rule.
