### ISSUE TITLE
Pulling kubectl from a container rather than a URL

### ISSUE THREAD

**Issue by jfautley** [KongZ/charts#30]
I've hit the same issue as documented (and fixed) in #25, but my proposed fix is slightly different (and in my opinion, better 😄)

Rather than pulling from a URL, I switched the init container image to `bitnami/kubectl:<version>` - a vaguely-official upstream image containing the latest kubectl binaries, and updated the init script to copy the binary from there.
This completely removes the need to pull the `kubectl` binary from an external service (removing any risk of potentially transient internet issues, handling proxy configuration in restricted networks, etc.)

I'm happy to submit a PR to implement the above, if it sounds like something you'd be happy with. 

The Bitnami images contain 'just enough' operating system for the other init commands to function as expected, as they're based on minideb - there's no significant size/traffic increase compared to the existing setup, and caching docker images locally is much easier in large scale environments than needing a static internal webserver (in my experience)!

**Comment by KongZ** [comment]
Pulling image from docker hub is also consider as an external service which you will have the same networking issue. You may also hit the pulling limit too.

The `bitnami` is not official `kubectl` release. Download directly from Kubernetes host is better. Also using external docker image has a risk of compromised image which attackers may put a malicious binary into the image.

**Comment by jfautley** [comment]
Fair enough - will close 🤷‍♂️
