### ISSUE TITLE
Dynamic provisioning for standalone

### ISSUE THREAD

**Issue by Surote** [KongZ/charts#38]
Hi everyone,

I try to use this chart with K8s with nfs dynamic provisioning PV. 
I found that for graylog it's ok for dynamic provision PV. what about elasticsearch and mongodb that build in in the chart. 
Is it has values for configure the storageclass like graylog?

**Comment by JVMartin** [comment]
Just install your own ES + MongoDB from their helm charts directly, that's how I did it.

**Comment by KongZ** [comment]
The Elasticsearch and MongoDB are external resources. If you want to configure them, you have to install them separately and set the values in Graylog helm chart pointing to them. :)
