### ISSUE TITLE
Unable to get elasticsearch working

### ISSUE THREAD

**Issue by NicoKuroKusagi** [KongZ/charts#42]
Installed using the helm chart, stuck at this:

{
  "cluster_name" : "elasticsearch",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 5,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : "NaN"
}

Graylog shows Elasticsearch cluster is red. Shards: 0 active, 0 initializing, 0 relocating, 0 unassigned

Any ideas how to get this fixed or where to start debugging?

**Comment by KongZ** [comment]
You can check out Elasticsearch error by `kubectl logs ${es-pods}` to see what is wrong in the ES server.
This is the Elasticsearch problem. You should raise the question Elasticsearch chart owner. :)
