### ISSUE TITLE
Not able to see the results in UI

### ISSUE THREAD

**Issue by lavanyakondamoni** [KongZ/charts#46]
When deploying the Graylog using helm chart, Not able to see the logs in the UI.
-->

**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version:v3.4.0+g7090a89
kubernetes: 1.19

```console
$ helm version

v3.4.0+g7090a89
```

Kubernetes Version:

```console
$ kubectl version
```
v1.19.7
**Which version of the chart**:

graylog         graylog         1               2021-06-08 14:03:13.269769401 +0000 UTC deployed        graylog-1.7.10          4.0.6
**What happened**:

Unable to see the Logs in the ui

**What you expected to happen**:

I should able to see the logs in UI

**How to reproduce it** (as minimally and precisely as possible):

Deploy the helm chart and expose it using loadbalncer.

**Anything else we need to know**:
<img width="960" alt="graylog_github" src="https://user-images.githubusercontent.com/82899196/121231893-95eaf480-c8ae-11eb-8c98-87037dcf27c4.png">
<img width="949" alt="gratlog_upload" src="https://user-images.githubusercontent.com/82899196/121232286-11e53c80-c8af-11eb-9f26-3c82c6fb3d42.PNG">

**Comment by lavanyakondamoni** [comment]
> When deploying the Graylog using helm chart, Not able to see the logs in the UI.
> -->
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Version of Helm and Kubernetes**:
> 
> Helm Version:v3.4.0+g7090a89
> kubernetes: 1.19
> 
> ```
> $ helm version
> 
> v3.4.0+g7090a89
> ```
> 
> Kubernetes Version:
> 
> ```
> $ kubectl version
> ```
> 
> v1.19.7
> **Which version of the chart**:
> 
> graylog graylog 1 2021-06-08 14:03:13.269769401 +0000 UTC deployed graylog-1.7.10 4.0.6
> **What happened**:
> 
> Unable to see the Logs in the ui
> 
> **What you expected to happen**:
> 
> I should able to see the logs in UI
> 
> **How to reproduce it** (as minimally and precisely as possible):
> 
> Deploy the helm chart and expose it using loadbalncer.
> 
> **Anything else we need to know**:> <img alt="graylog_github" width="960" src="https://user-images.githubusercontent.com/82899196/121231893-95eaf480-c8ae-11eb-8c98-
87037dcf27c4.png">
> <img alt="gratlog_upload" width="949" src="https://user-images.githubusercontent.com/82899196/121232286-11e53c80-c8af-11eb-9f26-3c82c6fb3d42.PNG">

**Comment by KongZ** [comment]
This look like a problem with your Elasticsearch. It does not related to the helm chart. 
I will close the issue. Please reopen it if you think the chart is incorrect.
