### ISSUE TITLE
web-UI of graylog throwing an error for version less than current of 4.1.0 ( current in chart is 4.0.6 ) 

### ISSUE THREAD

**Issue by ca8IiN4oow** [KongZ/charts#50]
**Describe the bug**
web-UI of graylog throwing an error for version less than current of 4.1.0 ( current in chart is 4.0.6 ) 

" You are running an outdated Graylog version. (triggered an hour ago)
The most recent stable Graylog version is 4.1.0 (Noir) released at 2021-06-23T00:00:00.000Z. Get it from https://www.graylog.org/." 

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}


```

**Which version of the chart**:
both version: 1.7.10 and version: 1.7.11

**What happened**:
The alerts bell had an alert so I went and looked at it. 

**What you expected to happen**:
No alert bell? 

**How to reproduce it** (as minimally and precisely as possible):
Reinstall a fresh instance. 

**Anything else we need to know**:

**Comment by KongZ** [comment]
You can change `graylog.image.repository` to 4.1.0 if you want to use the latest version without new version notice.
The default value in this chart is set to the latest tested version.
