### ISSUE TITLE
MongoDB frequent restarts

### ISSUE THREAD

**Issue by CoMaDaniel** [KongZ/charts#51]
Hello.

Sorry to disturb you, maybe someone can help me.
I have deployed the graylog chart, with an external Mongodb, with architecture replicaset.
The problem I have is that MongoDB ends up using a lot of resources, making the whole k8s cluster unstable. Giving the fact that we are limited in that regard, I have chosen to limit the resources consumed by Mongo. Now, I get frequent restarts (5 per day, every time it tries to go over the limit, set to 256Mi).
Is there any way of fixing that? Seems strange, as I only have one replica of Graylog and one of MongoDB running, and it should be pretty light in consuming resources.
Would letting the chart deploy Mongo itself be better? Maybe it has something to do with graylog.persistence.enabled=false (I'm fuzzy on this one, which data is not to be persisted, as I have both Mongo and Elasticsearch persisted separately)?

The command used for Graylog deployment:
helm upgrade --install graylog kongz/graylog --namespace test--set graylog.replicas=1 --set graylog.persistence.enabled=false  --set graylog.image.repository=graylog/graylog:3.3 --set tags.install-elasticsearch=false --set tags.install-mongodb=false --set graylog.elasticsearch.hosts=http://elasticsearch-master.test.svc.cluster.local:9200 --set graylog.mongodb.uri=mongodb:// mongodb-mongodb-replicaset.test.svc.cluster.local:27017/graylog?replicaSet=rs0 --set graylog.ingress.enabled=true --set graylog.ingress.port=9000 --set graylog.ingress.hosts.0=graylogtest.org --set graylog.externalUri=graylogtest.orgl --set graylog.input.tcp.service.type=ClusterIP --set graylog.input.tcp.ports[0].name=gelf1 --set graylog.input.tcp.ports[0].port=12201

Thanks for the help!

**Comment by KongZ** [comment]
Sorry, if you are still need help, please feel free to reopen.
This issue is not related to the Graylog chart. I would suggest to check the Mongodb pods events why it was restarted. Probably memory limits as you said. In this case, you should increase a MongoDb memory limits. Using MongoDB from chart dependency or external mongodb are not different.
