### ISSUE TITLE
Journal Size not configurable

### ISSUE THREAD

**Issue by romulus-ai** [KongZ/charts#53]
**Describe the bug**
The Helm chart is not able to configure the size of the journal. By default this is 5GB, however, there are cases, especially in K8S (i.e. when all filebeats are restarted at once), where massive peaks needs to be handled. Here a bigger journal size is a must have.

**Version of Helm and Kubernetes**:

Helm Version: 
version.BuildInfo{Version:"v3.3.0-rc.1", GitCommit:"5c2dfaad847df2ac8f289d278186d048f446c70c", GitTreeState:"dirty", GoVersion:"go1.14.4"}

Kubernetes Version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Which version of the chart**:
graylog-1.7.11

**What happened**:
See above, its not a bug, its a feature request.

**What you expected to happen**:
Make journal size configurable

**How to reproduce it** (as minimally and precisely as possible):
**Anything else we need to know**:

**Comment by CVirus** [comment]
You can do something like:

```
graylog:
    config: |
      message_journal_max_age = 168h
      message_journal_max_size = 19gb
```

**Comment by romulus-ai** [comment]
Ah, I saw this too late and I did not see it in the Readme. So may this change was merged too fast. However thank you anyway!
