### ISSUE TITLE
Upgrade Chart to most recent GrayLog Version

### ISSUE THREAD

**Issue by gprossliner** [KongZ/charts#57]
Please upgrade the default Image to 4.1.2.
Images are available: https://hub.docker.com/r/graylog/graylog/tags?page=1&ordering=last_updated

Why don't you use the Maior.Minor Tag, like 4.0 or 4.1? Then you would need to update the Chart not so frequently
I've seen that it's documented in the source:  https://github.com/KongZ/charts/blob/cc3526cf9b98ed29bd0776cc20b80f55e02bb850/charts/graylog/values.yaml#L53
But I don't understand why. Are the any specific Upgrade routines needed?

Thanks

**Comment by KongZ** [comment]
You can upgrade graylog image version by overriding `graylog.image.repository`. 
The default version will be updated when it is tested.
You are welcome to help testing the new version and submit a PR too. :)

> Why don't you use the Maior.Minor Tag, like 4.0 or 4.1? Then you would need to update the Chart not so frequently

The image tag is mutable and from the pass experience, sometime Graylog replaced a new image version with same tag name. And sometime, minor version is not compatible with same minor version e.g. `4.0.1-2` broke the entry point but `4.0.1-1` is runnable. (the version number is just an example, i don't really remember which version we faced this problem. But it happened twice). According to Graylog docs, `-x` suffix indicate changing in Dockerfile but same Graylog version.

**Comment by gprossliner** [comment]
Ok, thanks! Is the test procedure documented somewhere?

**Comment by KongZ** [comment]
Sorry, for late. Usually, we just make sure the new version is able to run with this chart (start,logging,search) and probably testing on some plugins. For some example, they change the plugins location on 4.0 so it break charts plugin installation script.

I've tested and bump to 4.1.3 on #61
