### ISSUE TITLE
Remove deprecated Elasticsearch dependency

### ISSUE THREAD

**Issue by oscarlofwenhamn** [KongZ/charts#6]
**Describe the bug**
Chart should use the [official Elasticsearch chart](https://github.com/elastic/helm-charts/tree/master/elasticsearch) instead of deprecated `stable/elasticsearch`.

**Which version of the chart**:
1.7.0

**Up for debate**:
I'm not sure if a migration tool should be looked into, if needed, to make it easier to update for users running the deprecated Elasticsearch version.

**Comment by maranmaran** [comment]
+1

**Comment by dmitriy-lukyanchikov** [comment]
+1

**Comment by kbiernat** [comment]
Does that have anything to do with the Elasticsearch not really working at this point, out of the box?
The ES cluster health is red and I can't seem to be able to do anything about it.
IMHO if it's not working, it should not even be possible to try it.

**Comment by kbiernat** [comment]
There's still the issue that if you build a 'monitoring' chart, with this 'graylog', adding another 'elasticsearch' and 'mongo' as dependencies results in warning such as below on upgrades. This could be mitigated by setting the additional ES/Mongo as aliases, but it's only a workaround to silence errors for stuff that doesnt work anyway.

```
coalesce.go:199: warning: cannot overwrite table with non table for initContainers (map[])
coalesce.go:199: warning: cannot overwrite table with non table for sidecars (map[])
coalesce.go:199: warning: cannot overwrite table with non table for image (map[pullPolicy:IfNotPresent repository:docker.elastic.co/elasticsearch/elasticsearch-oss tag:6.8.13])
``
