### ISSUE TITLE
Hello, thanks, but you need to change the syntax of the ingress as well, this is changed in the new api:

### ISSUE THREAD

**Issue by ws-prive** [KongZ/charts#65]
Hello, thanks, but you need to change the syntax of the ingress as well, this is changed in the new api:

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0]): missing required field "pathType" in io.k8s.api.networking.v1.HTTPIngressPath]

_Originally posted by @ws-prive in https://github.com/KongZ/charts/issues/63#issuecomment-903957924_

**Comment by KongZ** [comment]
@tlperini thanks for reporting. it was my wrong typo. Fixed
