### ISSUE TITLE
[graylog] Add priorityClass definitions

### ISSUE THREAD

**Issue by tlperini** [KongZ/charts#71]
**Describe the bug**
There is no way to configure priority classes for the Graylog Helm Chart pods.

**Version of Helm and Kubernetes**:

Helm Version: 3.5.0

Kubernetes Version: v1.18.20

**Which version of the chart**:  1.7.10

**What happened**:   Need to set priority to the Graylog pods using K8s priority classes.

**What you expected to happen**: A way to set the priorityClassName for the pods in values.yaml

**Describe the solution you'd like** (as minimally and precisely as possible):

Add the graylog.priorityClassName parameter in values.yaml.
This parameter should be defined in the statefulset spec:
```
 template:
    ...
    spec:
      ...
      containers:
      ...
      priorityClassName: {{ .Values.priorityClassName }}
```

**Comment by alex-bes** [comment]
Hi there, any chances this will be added soon?

**Comment by KongZ** [comment]
done
