### ISSUE TITLE
/entrypoint.sh: line 17: /k8s/kubectl: No such file or directory

### ISSUE THREAD

**Issue by chuegel** [KongZ/charts#83]
**Describe the bug**
Entrypoint points to a static kubectl file inside the pod and fails:
`/entrypoint.sh: line 17: /k8s/kubectl: No such file or directory`

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
flux helm-controller 0.12.1
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**Which version of the chart**:
1.8.10

**What happened**:
graylog fails to determine the MASRTER IP when running with multiple replicas because the entrypoint.sh configmap points to a missing `kubectl`file

```
MASTER_IP=`/k8s/kubectl --namespace graylog get pod -o jsonpath='{range .items[*]}{.metadata.name} {.status.podIP}{"\n"}{end}' -l graylog-role=master --field-selector=status.phase=Running|awk '{print $2}'`
SELF_IP=`/k8s/kubectl --namespace graylog get pod $HOSTNAME -o jsonpath='{.status.podIP}'`
```

inside the pod:
```
graylog@graylog-0:~$ ls -la /k8s/
total 0
drwxrwxrwx. 2 root root  6 Nov 15 17:00 .
drwxr-xr-x. 1 root root 71 Nov 15 17:03 ..
```

**What you expected to happen**:
Graylog cannot run with replicas as the master ip fails to

**How to reproduce it** (as minimally and precisely as possible):
see above

**Anything else we need to know**:

**Comment by KongZ** [comment]
Some Kubernetes cluster such as EKS has their own Kube version. So the chart could not find the matching kubectl version. You have to specify `graylog.init.kubectlVersion` version on values

For example:
```
graylog
  init:
    kubectlVersion: "v1.19.13"
```

**Comment by chuegel** [comment]
Yes, setting the version fixed it. Thank you
