### ISSUE TITLE
same loadBalancerIP reused in both web and master templates

### ISSUE THREAD

**Issue by jgc234** [KongZ/charts#9]
I'm unsure what's supposed to happen if you set the the service.type to LoadBalancer and set the loadBalancerIP.

The templates appear set up to support this, however web-service.yaml and master-service.yaml re-use the same IP address (graylog.service.loadBalancerIP) for both services in this case.

Was the master service supposed to have a separate address, or did I misunderstand the intent of the configuration?

**Comment by KongZ** [comment]
This was fixed on #75
